 # YAML

 ################################################################
 #NOTE: All paths must be absolute from the input mapped volume #
 ################################################################


# General options
#################
 # varMDsim, varScaffold, drugSearch, or varAnalysis
mode: varAnalysis

 #Name of protein system
protein: PDL1

 #Variant as "wt" or "x###x" - (OPTIONAL for varAnalysis)
variant: wt

#varResID + varAA override variant field. If one is filled, the other must be filled, or variant field used
 #variant residue ID from PDB template
varResID: 

 #amino acid to change
varAA: 

 #if Run is on CGC platform, move pdb and log to snp2sim root for processing
cgcRun:

runDIR: /Users/vikram/Documents/georgetown/summer_2019/run_workflow/snp2simresults

#Overwrite previous run with same protein name.
clean: 



# Mode specific options

# varMDsim options
##################

 #path to cleaned PDB file (protein structure w/ cannonical aa)
newStruct:

 #varTraj simulation length in ns
simLength: .05

 #amino acid to change
simID:

 #number of processors to run simulation
simProc:

 #output summary PDB trajectory only
singleRun:

 #Only generate initial structures, without MD simulation
genStructures:


#Paths to executables. Ignore if using Docker.

 #path to VMD executable
VMDpath: /Applications/VMD\ 1.9.3.app/Contents/Resources/VMD.app/Contents/MacOS/VMD

 #path to AutoDock Vina executable
VINApath:

 #path to NAMD executable
NAMDpath:

 #path to autodock tools python executable
PYTHONSHpath:

 #path to autodock utilities directory
ADTpath:



# varScaffold
#############

 #unique identifier for run
scaffID: test

 #Use PDB trajectories (possibly from singleCGC runs)
clustPDBtraj: true

 #pdb trajectory files to import, list one after another
loadPDBtraj:

#Cluster Parameters - follow VMD atomselection format
#Residues to superimpose trajectory 
alignmentResidues: backbone and resid 19 to 131
#Residues to consider when clustering trajectory
clusterResidues: backbone and resid 19 20 54 56 66 68 115 116 117 121 122 123 124 125

featureTableMethod: true
#if mds method used
PairwiseRMSD: 

colorTrajectory: 



# drugSearch
############

 #path to PDB file used to create search space to align scaffold
bindingTemplate:

 #exhaustiveness parameter of autodock vina
vinaExh:

 #path to new binding config file
newBindingConfig:

 #Automatically determine the search box based on the 
autoSearchSpace: 

 #list of residues that comprise the search space if autoSearchSpace is true, e.i 22 21 19 103 113 125
searchResidues:

 #list of residue numbers in flexible binding pocket, e.i 22 21 19 103 113 125
flexBinding:

 #name of snp2sim drug library
drugLibrary:

 #path to single drug PDBQT
singleDrug:

 #pdb scaffold files to import, list one after another
inputScaff:

 #only bind single variant scaffolds
bindSingleVar:

 #path to dir with ligand PDBs, which will be converted to drug library
ligandPDB:

 #number of times to run the docking simulation, to get an uncertainty measurement of the binding energy
numTrials: 6

# varAnalysis
############

 #Variants to be used in variants (must have a results/variant/drugBinding directory with .pdbqt results)
 #Format ###AA (### = residue number and AA = variant amino acid) or wt
 #must include wt
analysisVariants: 
  - 53P
  - 68L
  - 86W
  - 94M
  - 95R
  - 97V
  - 115T
  - wt

 #Analyze results from specific drug libraries
analysisDrugLibrary: 

 #Analyze results from a specific ligand
analysisDrug:

 #Enable if using scaffolding results from old versions of SNP2SIM
legacyScaff:

 #Enable if using drugBinding results from custom PDB proteins, and not varScaffold results
customScaff: 
