 # YAML

 # varMDsim, varScaffold, drugSearch, or varAnalysis
mode: varMDsim

 #Name of protein system
protein: KRAS

 #Variant as "wt" or "x###x"
variant: wt

 #path to cleaned PDB file (protein structure w/ cannonical aa)
newStruct: 

 #path to PDB file used to create search space to align scaffold
bindingTemplate:

 #path to scaffold config (search RMSD and # iterations, alignment aa, clusteraa
newScaff:

 #varTraj simulation length in ns
simLength:

 #variant residue ID from PDB template
varResID:

 #amino acid to change
varAA:

 #exhaustiveness parameter of autodock vina
vinaExh:

 #exhaustiveness parameter of autodock vina
clustThresh:

 #amino acid to change
simID:

 #name for autodock template config (search space and alignment res)
bindingID:

 #name of scaffolding parameters set
scaffID:

 #path to VMD executable
VMDpath:

 #path to AutoDock Vina executable
VINApath:

 #path to NAMD executable
NAMDpath:

 #path to autodock tools python executable
PYTHONSHpath:

 #path to autodock utilities directory
ADTpath:

 #path to new binding config file
newBindingConfig:

 #path to file with flex residue numbers
flexBinding:

 #name of snp2sim drug library
drugLibrary:

 #path to single drug PDBQT
singleDrug:

 #number of processors to run simulation
simProc:

 #output summary PDB trajectory only
singleRun:

 #cluster results from multiple varScafold singleRun
clustPDBtraj:

 #pdb trajectory files to import, list one after another
loadPDBtraj:

 #pdb scaffold files to import, list one after another
inputScaff:

 #if Run is on CGC platform, move pdb and log to snp2sim root for processing
cgcRun:

 #only bind single variant scaffolds
bindSingleVar:
